# server:
#   port: 9090
  # ssl:
  #   enabled: false
  #   key-store: ./keystore.p12
  #   key-store-password: your-password
  #   key-store-type: PKCS12

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#Eureka client        
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://eureka-server:8761/eureka/
#     healthcheck:
#       enabled: true
#   instance:
#     appname: apigateway
#     prefer-ip-address: true
#     lease-renewal-interval-in-seconds: 20
#     lease-expiration-duration-in-seconds: 60
# spring:
#   cloud:
#     gateway:
#       default-filters:
#         - TokenRelay
#       routes:
#         - id: user-service
#           uri: http://user-service:9091
#           predicates:
#             - Path=/api/user/**  
#         - id: book-service
#           uri: http://book-service:9195
#           predicates:
#             - Path=/api/rows      
#diennt      

spring:
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://10.82.14.80:8080/realms/DCMS-Realm
            #authorization-uri: https://10.82.14.80:9443/realms/DCMS-Realm
            # Individual properties can also be provided this way
   #         token-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/token

        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: spring-gateway-client
            client-secret: 8jygr7B4q5NdnGjKviREZxM227spjiix
            authorization-grant-type: authorization_code
            #redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
# Enable these to debug the Authorization flow
logging:
    level:
      org:
        springframework:
          security:
            web: DEBUG
          hibernate: ERROR
    file:
      name: logs/application-debug.log
      max-size: 2MB
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
